### ISSUE TITLE
The "prometheus-klipper-exporter-linux-amd64-v0.5.0" binary doesn't seem to be valid

### ISSUE THREAD

**Issue by wywywywy** [scross01/prometheus-klipper-exporter#1]
After downloading and running the `prometheus-klipper-exporter-linux-amd64-v0.5.0` binary, it does not execute.

```
bash: ./prometheus-klipper-exporter-linux-amd64-v0.5.0: cannot execute binary file: Exec format error
```

Perhaps it got mixed up with the macos format one during release stage?

Compiling manually with `make build` and `make release` work fine.

**Comment by scross01** [comment]
Found problem. Typo in Makefile.

**Comment by scross01** [comment]
Regenerated builds for `prometheus-klipper-exporter-linux-amd64-v0.5.0` and `prometheus-klipper-exporter-rpi-arm64-v0.5.0`
