### ISSUE TITLE
Merge similar metrics into single ones with labels.

### ISSUE THREAD

**Issue by Cova** [scross01/prometheus-klipper-exporter#10]
Metrics like klipper_temperature_fan_*_speed, or klipper_temperature_sensor_*_temperature, should be using labels rather than uniquely named metrics.  I have a bunch of printers with extra fans/thermistors in them in various places, and it is resulting in a very large number of metrics which mostly have empty values as that sensor only exists in a single machine.

I would much prefer just a klipper_temperature_sensor{sensor="*"} style of metric to work with.

**Comment by scross01** [comment]
Made some initial changes to address this in the `metrics_with_labels` branch.

**Comment by scross01** [comment]
Fixed in `v0.7.0`
