### ISSUE TITLE
List of custom temperature sensors is not updated for multiple printers.

### ISSUE THREAD

**Issue by Cova** [scross01/prometheus-klipper-exporter#11]
I have configured prometheus to query my printers like this (DNS is all configured correctly - everything works):

    static_configs:
      - targets:
        - 'voron:7125'
        - 'v18:7125'
        - 'sf160:7125'

However in the results I get back for klipper_temperature_sensor_* metrics, it is not looking at what custom metrics are available on the 'v18' or 'sf160' printers - it is getting the list of sensor names from "voron", and then querying all 3 printers for values for that sensor.  As they don't share any common names for their custom sensors, that results in empty metrics for the later printers having the names of sensors of the first printer, and also no metrics at all for the sensors of the later printers.

**Comment by scross01** [comment]
Fixed in `v0.7.0`
