### ISSUE TITLE
Temperature metrics error

### ISSUE THREAD

**Issue by maziggy** [scross01/prometheus-klipper-exporter#14]
Enabling temperature metrics are generating error.

An error has occurred while serving metrics:

6 error(s) occurred:
* collected metric klipper_extruder_temperature gauge:<value:249.69 >  has help "Klipper extruder temperature." but should have "Klipper extruder temperature"
* collected metric klipper_extruder_target gauge:<value:250 >  has help "Klipper extruder target." but should have "Klipper extruder target"
* collected metric klipper_extruder_power gauge:<value:0.08908521184983054 >  has help "Klipper extruder power." but should have "Klipper extruder power"
* collected metric klipper_heater_bed_temperature gauge:<value:110.15 >  has help "Klipper heater bed temperature." but should have "Klipper heater_bed temperature"
* collected metric klipper_heater_bed_target gauge:<value:110 >  has help "Klipper heater bed target." but should have "Klipper heater_bed target"
* collected metric klipper_heater_bed_power gauge:<value:0.22654915416571025 >  has help "Klipper heater bed power." but should have "Klipper heater_bed power"

**Comment by scross01** [comment]
The `temperature` module contains a subset of the metrics reported by the `printer_objects` module. The two modules cannot be configured together. See #2 

The `temperature` module will be removed in a future update.
