### ISSUE TITLE
configure log level?

### ISSUE THREAD

**Issue by RURon** [scross01/prometheus-klipper-exporter#17]
Hello, is there a way to modify the loglevel so you can control what is emitted to syslog? Mine is flooded with info messages so that I currently removed all logging from within rsyslog.conf by excluding the programname - not elegant.

Great tool otherwise!

**Comment by scross01** [comment]
v0.9.0 adds a new `-logging.level <level>` command line option to set the specific log output level. You can set to `Warn` level to skip the Info level logs.
